# Site settings
title: Diego Mallo
email: dmalload@asu.edu
description: "Web page of Diego Mallo @ Carlo Maley's lab. Cancer phylogenetics and species tree reconstruction methods."
keywords: "cancer phylogenetics, somatic evolution, phylogenetics, phylogenomics, evolutionary biology, simulation, species tree, gene tree, Carlo Maley, David Posada, Diego Mallo"
author: "Diego Mallo"

#Jekyll options
include: ["_pages"]
permalink: pretty
baseurl: /dmalloweb.github.io

#My collections
collections:
  papers:
    output: false
  projects:
    output: true
  software:
    output: true
  courses:
    output: true

defaults:
  - scope:
      type: software
    values:
      layout: software_page
  - scope:
      type: courses
    values:
      layout: course_page
  - scope:
      type: projects
    values:
      layout: default ##This may change to project in the future if I have a specific layout

#Options for running Jekyll locally
port: 3000 # change server port to 3000
