# Site settings
title: Diego Mallo
email: dmalload@asu.edu
description: "Web page of Diego Mallo @ Carlo Maley's lab. Cancer phylogenetics and species tree reconstruction methods."
keywords: "cancer phylogenetics, somatic evolution, phylogenetics, phylogenomics, evolutionary biology, simulation, species tree, gene tree, Carlo Maley, David Posada, Diego Mallo"
author: "Diego Mallo"

#Jekyll options
include: ["_pages"]
permalink: /:title/
baseurl: /dmalloweb.github.io

#Options for running Jekyll locally
port: 3000 # change server port to 3000
